### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by aaronsmith203** [philhk/hidive-downloader#4]
When I try to follow the video , I get an error in the terminal:

npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ npm install
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by philhk** [comment]
You need to install NodeJS first, sorry for not clarifying. Here is a link where you can download it from https://nodejs.org/en/download/.
