### ISSUE TITLE
 Is this API Key still correct?

### ISSUE THREAD

**Issue by macgyverisms** [philhk/hidive-downloader#5]
I ran hidive-downloader 1.0.0 on my Mac terminal, but after selecting the API Key it doesn't go any further. I'm sent back to Login.

Today, is HIDIVE's API Key still correct with API Key ( 508efd7b42d546e19cc24f4d0b414e57e351ca73 ) included in hidive-downloader 1.0.0?

**Comment by macgyverisms** [comment]
I'm sorry.

I was able to successfully download HIDIVE videos in terminal on mac (just had to replace ffmpeg for mac).

**Comment by Cambo0** [comment]
Hello, I'm having the same issue now, and would like to know about your solution, like know how do you 

> replace ffmpeg for mac

I downloaded mac version ffmpeg and FFprobe and FFplay from ffmpeg official website , and then replace the three .exe files in the original ffmpeg folder?

I tried the above, but now I still stuck at the initial Login/API menu. I would like to know how you solved this issue.
